export const GET_TODOS_START = "GET_TODOS_START"
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS"
export const GET_TODOS_FAIL = "GET_TODOS_FAIL"


export const ADD_TODO_START = "ADD_TODO_START"
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS"
export const ADD_TODO_FAIL = "ADD_TODO_FAIL"

export const EDIT_TODO_START = "EDIT_TODO_START"
export const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS"
export const EDIT_TODO_FAIL = "EDIT_TODO_FAIL"

export const DELETE_TODO_START = "DELETE_TODO_START"
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS"
export const DELETE_TODO_FAIL = "DELETE_TODO_FAIL"

export const SET_CURRENT_TODO_ID = "SET_CURRENT_TODO_ID"
